<x-layouts.landing>
    @include('landing.partials.navbar')
    @include('landing.partials.hero')
    @include('landing.partials.how')
    @include('landing.partials.features')
    @include('landing.partials.pricing')
    @include('landing.partials.cta')
    @include('landing.partials.footer')
</x-layouts.landing>
